### PR TITLE
Add version

### PR DESCRIPTION
**Pull request by xvilo**

### CODE REVIEW

**Comment by xvilo** [comment]
Should be fine and it will autopack CRX3 now

**Comment by xvilo** [comment]
https://github.com/PavelVanecek/gulp-crx/issues/26

**Comment by xvilo** [comment]
confirmed, builds with this version in our private pipelines :D

**Review by PavelVanecek — APPROVED** [review]
Hello and thanks for the PR!

**Comment by dnrce** [comment]
@PavelVanecek could you please push this new version to npm? Thanks!

**Comment by alvarotrigo** [comment]
This was never published in npm?
The latest in npm is 1.0.2
https://www.npmjs.com/package/gulp-crx-pack

**Comment by PavelVanecek** [comment]
I will give it a try today

**Comment by PavelVanecek** [comment]
Published 1.0.3

**Comment by alvarotrigo** [comment]
Thanks! 👍

**Pull request merged**
